version: '3.8'

services:
  proxy:
    build: .
    container_name: proxy
    networks:
      - lab-rede
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true
    # Comando para iniciar o túnel no modo servidor 
    command: ["traffic_tunnel", "eth0", "-s"]

  client:
    build: .
    container_name: client1
    networks:
      - lab-rede
    depends_on:
      - proxy
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true
    volumes:
      # Monta o script de configuração do cliente
      - ./client.sh:/app/client.sh
    # Comando para iniciar o túnel no modo cliente 
    command: ["traffic_tunnel", "eth0", "-c", "/app/client.sh"]

networks:
  lab-rede:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.27.0.0/16
        - subnet: "fd00:0:0:1::/64"